server:
  port: 8002

spring:
  application:
    name: analytics-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
