"use client";

import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import { Badge } from "@/components/ui/Badge";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/Card";
import {
  FEATURE_RANGES,
  FIELD_CONFIGS,
  type FeatureContribution,
  type PredictionResult,
  type PropertyFeatures,
} from "@/lib/schemas/estimator";

export interface ResultDisplayProps {
  /** Successful prediction payload (envelope `data` already unwrapped). */
  result: PredictionResult;
  /** The feature values that produced this prediction, if available. */
  features: PropertyFeatures | null;
}

/**
 * Renders the predicted price as a prominent headline plus a tabular
 * feature breakdown and a Recharts bar chart.
 *
 * Two chart modes:
 *  - When `result.contributions` is populated (Phase 3 wiring), the chart
 *    shows each feature's signed contribution to the predicted price, with
 *    positive bars in emerald and negative bars in red, plus a zero
 *    reference line.
 *  - Otherwise (Phase 2 fallback), the chart shows each feature value
 *    normalised to a 0–100 scale using `FEATURE_RANGES`, so the user still
 *    gets a visual sense of how extreme each input is.
 *
 * Accessibility:
 *  - The table uses `<caption>`, `scope="col"`, and `scope="row"` so screen
 *    readers can navigate the grid.
 *  - The chart is decorative; `aria-hidden` is set on the SVG container and
 *    a textual summary precedes it.
 */
export function ResultDisplay({ result, features }: ResultDisplayProps) {
  const hasContributions =
    Array.isArray(result.contributions) && result.contributions.length > 0;

  const tableRows = buildTableRows(result, features);
  const chartData = hasContributions
    ? buildContributionChartData(result.contributions!)
    : buildNormalisedChartData(features);

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardHeader>
          <CardTitle>Estimated Value</CardTitle>
        </CardHeader>
        <CardContent>
          <p
            className="text-3xl font-bold text-primary-700"
            data-testid="predicted-price"
          >
            {formatPrice(result.predicted_price)}
          </p>
          <p className="mt-1 text-xs text-slate-500">
            Generated by the regression model served from the estimator-api.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Feature Breakdown</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm">
              <caption className="sr-only">
                Property features used for this prediction
              </caption>
              <thead>
                <tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500">
                  <th scope="col" className="py-2 pr-4 font-medium">
                    Feature
                  </th>
                  <th scope="col" className="py-2 pr-4 font-medium">
                    Value
                  </th>
                  {hasContributions && (
                    <th scope="col" className="py-2 pr-4 font-medium">
                      Contribution
                    </th>
                  )}
                </tr>
              </thead>
              <tbody>
                {tableRows.map((row) => (
                  <tr
                    key={row.name}
                    className="border-b border-slate-100 last:border-0"
                  >
                    <th
                      scope="row"
                      className="py-2 pr-4 text-left font-medium text-slate-700"
                    >
                      {row.label}
                    </th>
                    <td className="py-2 pr-4 text-slate-900">
                      {row.value === null ? (
                        <span className="text-slate-400">—</span>
                      ) : (
                        `${row.value}${row.unit ? ` ${row.unit}` : ""}`
                      )}
                    </td>
                    {hasContributions && (
                      <td className="py-2 pr-4">
                        {row.contribution === null ? (
                          <span className="text-slate-400">—</span>
                        ) : (
                          <Badge
                            variant={row.contribution >= 0 ? "success" : "danger"}
                          >
                            {formatPrice(row.contribution)}
                          </Badge>
                        )}
                      </td>
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>
            {hasContributions ? "Price Contribution Chart" : "Feature Scale Chart"}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="mb-3 text-xs text-slate-500">
            {hasContributions
              ? "Each bar shows how much a feature adds to (or subtracts from) the predicted price."
              : "Each bar shows the input value normalised to a 0–100 scale based on the allowed feature range."}
          </p>
          <div
            className="h-72 w-full"
            aria-hidden="true"
            data-testid="chart-container"
          >
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={chartData}
                margin={{ top: 8, right: 16, bottom: 8, left: 0 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis
                  dataKey="label"
                  tick={{ fontSize: 11, fill: "#475569" }}
                  interval={0}
                  angle={-15}
                  textAnchor="end"
                  height={50}
                />
                <YAxis
                  tick={{ fontSize: 11, fill: "#475569" }}
                  width={hasContributions ? 70 : 40}
                />
                <Tooltip
                  cursor={{ fill: "rgba(148, 163, 184, 0.15)" }}
                  contentStyle={{
                    borderRadius: 8,
                    border: "1px solid #e2e8f0",
                    fontSize: 12,
                  }}
                  formatter={(
                    value: unknown,
                    _name: unknown,
                    payload: { payload?: { unit?: string } }
                  ) => {
                    const num = Number(value);
                    if (hasContributions) {
                      return [formatPrice(num), "Contribution"] as [string, string];
                    }
                    const unit = payload?.payload?.unit ?? "";
                    return [
                      `${num.toFixed(1)}${unit ? ` ${unit}` : ""}`,
                      "Normalised (0–100)",
                    ] as [string, string];
                  }}
                />
                {hasContributions && (
                  <ReferenceLine y={0} stroke="#94a3b8" />
                )}
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {chartData.map((entry, idx) => (
                    <Cell
                      key={idx}
                      fill={
                        hasContributions
                          ? entry.value >= 0
                            ? "#10b981"
                            : "#ef4444"
                          : "#6366f1"
                      }
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// ---- helpers -----------------------------------------------------------

interface TableRow {
  name: string;
  label: string;
  unit?: string;
  value: number | null;
  contribution: number | null;
}

function buildTableRows(
  result: PredictionResult,
  features: PropertyFeatures | null
): TableRow[] {
  const contributionByName = new Map<string, number>();
  if (Array.isArray(result.contributions)) {
    for (const c of result.contributions) {
      contributionByName.set(c.feature, c.contribution);
    }
  }

  return FIELD_CONFIGS.map((field) => {
    const value = features ? features[field.name] : null;
    const contribution = contributionByName.has(field.name)
      ? contributionByName.get(field.name)!
      : null;
    return {
      name: field.name,
      label: field.label,
      unit: field.unit,
      value,
      contribution,
    };
  });
}

interface ChartDatum {
  label: string;
  value: number;
  unit?: string;
}

function buildContributionChartData(
  contributions: FeatureContribution[]
): ChartDatum[] {
  // Order by absolute contribution descending so the most impactful
  // features appear first on the left of the chart.
  return [...contributions]
    .sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution))
    .map((c) => {
      const field = FIELD_CONFIGS.find((f) => f.name === c.feature);
      return {
        label: field?.label ?? c.feature,
        value: c.contribution,
        unit: field?.unit,
      };
    });
}

function buildNormalisedChartData(
  features: PropertyFeatures | null
): ChartDatum[] {
  if (!features) return [];
  return FIELD_CONFIGS.map((field) => {
    const range = FEATURE_RANGES[field.name];
    const raw = features[field.name];
    const span = range.max - range.min || 1;
    const clamped = Math.min(Math.max(raw, range.min), range.max);
    const normalised = ((clamped - range.min) / span) * 100;
    return {
      label: field.label,
      value: normalised,
      unit: field.unit,
    };
  });
}

function formatPrice(value: number): string {
  return value.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}
